# version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vendorhub-mssql
    environment:
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${MSSQL_ACCEPT_EULA}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - backend-net
    restart: always
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: vendorhub-redis
    ports:
      - "6379:6379"
    networks:
      - backend-net
      - frontend-net
    restart: unless-stopped
    # healthcheck (optional)
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendorhub-api-prod
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__sqlServerCs: "Server=mssql,1433;Database=${DB_NAME};User Id=${DB_USER};Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;Encrypt=false;"
      ConnectionStrings__RedisConnection: "redis:6379"
      JWT__SecritKey: ${JWT_SECRET_KEY}
      JWT__IssuerIP: ${JWT_ISSUER}
      JWT__AudienceIP: ${JWT_AUDIENCE}
      JwtOptions__IssuerIP: ${JWT_ISSUER}
    ports:
      - "7001:8080"

    depends_on:
      mssql:
        condition: service_started 
      redis:
        condition: service_started
    networks:
      - frontend-net
      - backend-net
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  # adminer:
  #   image: adminer
  #   container_name: vendorhub-adminer
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mssql
  #   networks:
  #     - frontend-net
  #     - backend-net
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mssql
  #   restart: unless-stopped



volumes:
  sqldata:
    driver: local

networks:
  frontend-net: 
  backend-net:
    internal: true